version: "3.5"

services:
  mongo-first-shard1:
    image: mongo:5.0
    container_name: mongo-first-shard1
    command: mongod --shardsvr --replSet rnd-first-shard-replica-set --port 27011
    ports:
      - "27011:27011"
  mongo-first-shard2:
    image: mongo:5.0
    container_name: mongo-first-shard2
    command: mongod --shardsvr --replSet rnd-first-shard-replica-set --port 27012
    ports:
      - "27012:27012"
  mongo-first-shard3:
    image: mongo:5.0
    container_name: mongo-first-shard3
    command: mongod --shardsvr --replSet rnd-first-shard-replica-set --port 27013
    ports:
      - "27013:27013"

  mongo-second-shard1:
    image: mongo:5.0
    container_name: mongo-second-shard1
    command: mongod --shardsvr --replSet rnd-second-shard-replica-set --port 27021
    ports:
      - "27021:27021"
  mongo-second-shard2:
    image: mongo:5.0
    container_name: mongo-second-shard2
    command: mongod --shardsvr --replSet rnd-second-shard-replica-set --port 27022
    ports:
      - "27022:27022"
  mongo-second-shard3:
    image: mongo:5.0
    container_name: mongo-second-shard3
    command: mongod --shardsvr --replSet rnd-second-shard-replica-set --port 27023
    ports:
      - "27023:27023"

  mongo-third-shard1:
    image: mongo:5.0
    container_name: mongo-third-shard1
    command: mongod --shardsvr --replSet rnd-third-shard-replica-set --port 27031
    ports:
      - "27031:27031"
  mongo-third-shard2:
    image: mongo:5.0
    container_name: mongo-third-shard2
    command: mongod --shardsvr --replSet rnd-third-shard-replica-set --port 27032
    ports:
      - "27032:27032"
  mongo-third-shard3:
    image: mongo:5.0
    container_name: mongo-third-shard3
    command: mongod --shardsvr --replSet rnd-third-shard-replica-set --port 27033
    ports:
      - "27033:27033"

  mongo-config-server1:
    image: mongo:5.0
    container_name: mongo-config-server1
    command: mongod --configsvr --replSet rnd-config-replica-set --port 27001
    ports:
      - "27001:27001"
  mongo-config-server2:
    image: mongo:5.0
    container_name: mongo-config-server2
    command: mongod --configsvr --replSet rnd-config-replica-set --port 27002
    ports:
      - "27002:27002"
  mongo-config-server3:
    image: mongo:5.0
    container_name: mongo-config-server3
    command: mongod --configsvr --replSet rnd-config-replica-set --port 27003
    ports:
      - "27003:27003"

  mongo-router:
    image: mongo:5.0
    container_name: mongo-router
    command: mongos --configdb rnd-config-replica-set/mongo-config-server1:27001,mongo-config-server2:27002,mongo-config-server3:27003 --port 27000 --bind_ip_all
    depends_on:
      - mongo-config-server1
      - mongo-config-server2
      - mongo-config-server3
    ports:
      - "27000:27000"
    volumes:
      - ./scripts:/scripts

  mongo-client:
    image: mongo:5.0
    container_name: mongo-client
    links:
      - mongo-router
    depends_on:
      - mongo-first-shard1
      - mongo-first-shard2
      - mongo-first-shard3
      - mongo-second-shard1
      - mongo-second-shard2
      - mongo-second-shard3
      - mongo-third-shard1
      - mongo-third-shard2
      - mongo-third-shard3
      - mongo-router
    volumes:
      - ./scripts:/scripts
    command:
      - /scripts/initiate-repl.sh
